spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/dhaka_run
    username: ${DB_USERNAME:dhaka_user}
    password: ${DB_PASSWORD:dhaka_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: DEBUG
app:
  datasource:
    openaq:
      api-key: b1cf900da62dc452a92e5208a2975d1e87f9940195f3d1bb36ce001369a3e09e
      base-url: https://api.openaq.org/v3
      timeout: 10s
